thecodingmachine/tdbm

- src/QueryFactory/FindObjectsFromSqlQueryFactory.php
- tests/Dao/TestUserDao.php
- tests/TDBMDaoGeneratorTest.php
See https://github.com/thecodingmachine/database.tdbm/pull/148
Credits to @dsavina for this heavy fix :)
> Porting ORDER BY fix to TDBM 5 

- src/Utils/BeanDescriptor.php
- tests/Fixtures/tdbmunittest.sql
> Fixes bug if a table has 2 similar indexes.

- src/Utils/BeanDescriptor.php
- tests/TDBMDaoGeneratorTest.php
PHP 7 scalar type-hints added.
> Adding type-hints to base bean constructors

- src/Utils/BeanDescriptor.php
- src/Utils/TDBMDaoGenerator.php
- tests/Dao/TestUserDao.php
Removing unused or no more existing classes from use statements and comments
> Cleaning code generation

- .travis.yml
- composer.json
- phpunit.postgres.xml
- src/DbRow.php
- src/QueryFactory/AbstractQueryFactory.php
- src/QueryFactory/FindObjectsFromSqlQueryFactory.php
- src/TDBMService.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/Dao/TestUserDao.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMSchemaAnalyzerTest.php
- tests/TDBMServiceTest.php
- tests/phpunit-pgsql.sh
... and fixing the codebase so that all tests are successful!
> Adding PostgreSQL tests

- src/QueryFactory/FindObjectsFromSqlQueryFactory.php
- src/TDBMService.php
- src/Utils/BeanDescriptor.php
- src/Utils/DirectForeignKeyMethodDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/Dao/TestRoleDao.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMServiceTest.php
> Adding a transaction in "save" method

- tests/TDBMAbstractServiceTest.php
Fix bug introduced in #43
Closes #44
> Fix oracle tests

- composer.json
- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- tests/Dao/TestCountryDao.php
- tests/TDBMDaoGeneratorTest.php
This is a failing test for https://github.com/thecodingmachine/database.tdbm/issues/153
> findFromRawSql does not support UNION queries

- src/AlterableResultIterator.php
- tests/TDBMDaoGeneratorTest.php
> Nested iterators are failing for many-to-one relationships

- src/Utils/AbstractBeanPropertyDescriptor.php
- src/Utils/BeanDescriptor.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/TDBMDaoGeneratorTest.php
Adding failing test for cloning UUID
> Cloning a bean with a UUID should generate a new UUID

- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- tests/Dao/TestCountryDao.php
- tests/TDBMDaoGeneratorTest.php
- Adding failing test related to bug #56
> DISTINCT queries are failing in "findFromRawSql"

- src/TDBMService.php
- src/Utils/BeanDescriptor.php
- tests/Dao/TestUserDao.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMSchemaAnalyzerTest.php
> Fixing find from indexes with foreign keys.

- composer.json
- phpstan.neon
- src/AbstractTDBMObject.php
- src/Commands/AlteredConfiguration.php
- src/Configuration.php
- src/DbRow.php
- src/InnerResultIterator.php
- src/OrderByAnalyzer.php
- src/ResultIterator.php
- src/StandardObjectStorage.php
- src/TDBMService.php
- src/Utils/BeanDescriptor.php
- src/Utils/DirectForeignKeyMethodDescriptor.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- src/Utils/PathFinder/PathFinder.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- src/Utils/TDBMDaoGenerator.php
- src/WeakrefObjectStorage.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMServiceTest.php
Slowly but steadily working on improving code by fixing issues from PHPStan.
One PHPStan level at a time :)
> Working towards reaching PHPStan level 7

- doc/install_laravel.md
- doc/install_lumen.md
Laravel package does not require an additional package anymore.
See https://github.com/thecodingmachine/tdbm-laravel/pull/1
> Fixing Laravel documentation

- composer.json
- phpstan.neon
- src/AbstractTDBMObject.php
- src/DbRow.php
- src/PageIterator.php
- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- src/TDBMService.php
- src/Utils/AbstractBeanPropertyDescriptor.php
- src/Utils/BeanDescriptor.php
- src/Utils/DefaultNamingStrategy.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- src/Utils/TDBMDaoGenerator.php
- vendor-bin/couscous/composer.lock
- vendor-bin/require-checker/composer.lock
... and to phpstan-strict-rules 0.10.1
> Switching to PHPStan 0.10

- CHANGELOG.md
- src/Utils/TDBMDaoGenerator.php
- tests/TDBMDaoGeneratorTest.php
This PR automatically purges the content of Generated namespaces on code generation.
This closes #55.
Ping @Zheness
> Automatic cleanup of generated beans and daos

- src/DbRow.php
- src/QueryFactory/FindObjectsQueryFactory.php
- src/TDBMService.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMSchemaAnalyzerTest.php
> Backporting fixing multiple primary key with foreign key issue

- src/Utils/DirectForeignKeyMethodDescriptor.php
- tests/TDBMDaoGeneratorTest.php
> Backport: Reverse relationship on beans with foreign key on non primary key fails

- src/QueryFactory/AbstractQueryFactory.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
> Fixing sort on child error

- src/Utils/TDBMDaoGenerator.php
findXXX methods are now type hinted to ResultIterator
> Improving type-hints

- doc/install_silex.md
- src/TDBMService.php
- tests/TDBMServiceTest.php
Display more info about the fields and values when a DuplicateRowException occurs. #120
> Add additional information when DuplicateRowException occurs

- phpunit.mariadb.xml
- phpunit.oracle.xml
- phpunit.postgres.xml
- phpunit.xml.dist
- src/TDBMService.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/phpunit-pgsql.sh
Otherwise, with the new namingstrategy, the model is fetched for each request!
> Caching table to bean relationship

- CHANGELOG.md
- doc/annotations.md
- src/Utils/Annotation/AnnotationParser.php
- src/Utils/Annotation/JsonCollection.php
- src/Utils/Annotation/JsonFormat.php
- src/Utils/Annotation/JsonIgnore.php
- src/Utils/Annotation/JsonInclude.php
- src/Utils/Annotation/JsonKey.php
- src/Utils/Annotation/JsonRecursive.php
- src/Utils/BeanDescriptor.php
- src/Utils/DirectForeignKeyMethodDescriptor.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- src/Utils/PivotTableMethodsDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/Utils/PivotTableMethodsDescriptorTest.php
Add annotations `@JsonSkip`, `@JsonInclude`, `@JsonFormat` for more control over generated method `jsonSerialize()` in beans.
> Feature: @Json annotations

- src/Utils/BeanDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
> fixed an issue with required parameters in findOneBy

- src/Utils/DirectForeignKeyMethodDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
After using this https://github.com/thecodingmachine/tdbm/pull/151 we found out that a plural getter name for a singular value wasn't the best.
This PR Singularize the getter name in OneToOne inverse relation
> OneToOne inverse relation: singular getter name

- doc/manual_install.md
> Fix manual install doc

- src/InnerResultIterator.php
- tests/TDBMDaoGeneratorTest.php
In InnerResultIterator TDBM doesn't send arrays parameter type to DBAL this result int a Notice "Array To String conversion"
This Merge Request Fix that notice
> SQLCountWithArray - ArrayToString conversion

- .gitignore
- composer.json
- phpbench.dist.sh
- phpbench.json
- tests/ConnectionFactory.php
- tests/Performance/ManyToOneBench.php
- tests/TDBMAbstractServiceTest.php
Adding first performance test using PHPBench.
Testing a ManyToOne relationship fetching inside a loop.
> Adding PHPBench performance test

- .travis.yml
- composer.json
- phpbench.dist.sh
- tests/Performance/ManyToOneBench.php
Added code to compare performances from current branch to master branch.
> Adding benchmark to CI

- composer.json
- src/Utils/AbstractBeanPropertyDescriptor.php
- src/Utils/BeanDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- src/Utils/StringUtils.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/Utils/StringUtilsTest.php
> Column starting with a digit (#184): Add test

- src/Utils/BeanDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
> DateTime filter (#189): Add test case

- phpstan.neon
- phpunit.mariadb.xml
- phpunit.mysql8.xml
- phpunit.oracle.xml
- phpunit.postgres.xml
- phpunit.xml.dist
- src/Configuration.php
- src/Schema/LockFileSchemaManager.php
- src/SchemaLockFileDumper.php
- src/TDBMSchemaAnalyzer.php
- src/TDBMService.php
- tests/Commands/AlteredConfigurationTest.php
- tests/Performance/ManyToOneBench.php
- tests/SchemaLockFileDumperTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMSchemaAnalyzerTest.php
- tests/Utils/BeanDescriptorTest.php
> Always read the schema from the lock file

- src/QueryFactory/FindObjectsQueryFactory.php
- tests/TDBMAbstractServiceTest.php
Improving tests performance by using cache.
In the process, I fixed a SQL subquery cache related bug.
> Improving test performance

- phpstan.neon
- src/QueryFactory/AbstractQueryFactory.php
- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- src/QueryFactory/FindObjectsFromSqlQueryFactory.php
- src/QueryFactory/QueryFactory.php
- src/SafeFunctions.php
- src/Schema/ForeignKey.php
- src/Schema/ForeignKeys.php
- src/Utils/Logs/LevelFilter.php
- src/Utils/RootProjectLocator.php
- src/Utils/StringUtils.php
- src/Utils/TDBMDaoGenerator.php
- tests/phpunit-oracle.sh
(and fixing the errors that were wrongly ignored)
> Fixing a PHPStan regex that was too wide

- .github/workflows/continuous-integration.yml
- composer.json
- couscous.yml
- doc/compatibility.md
- phpstan.neon
- phpunit.oracle.xml
- src/QueryFactory/AbstractQueryFactory.php
- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- src/SchemaLockFileDumper.php
- src/Utils/BeanDescriptor.php
- src/Utils/ColumnsReorderer.php
- src/Utils/TDBMDaoGenerator.php
- tests/ConnectionFactory.php
- tests/Dao/TestCountryDao.php
- tests/Fixtures/oracle-startup.sql
- tests/SchemaLockFileDumperTest.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/oracle/Dockerfile
- tests/phpunit-oracle.sh
- vendor-bin/couscous/composer.lock
- vendor-bin/require-checker/composer.lock
> Fixing Oracle unit tests

- doc/install_symfony.md
> Adding documentation to support several databases

- src/Utils/BeanDescriptor.php
- tests/TDBMAbstractServiceTest.php
> Fix - Avoid method name collision due to different cases

- phpstan.neon
- src/NoBeanFoundException.php
- src/TDBMService.php
- tests/TDBMServiceTest.php
Add some properties to the `NoBeanFoundException.php`, so a more structured information may bubble up while error is catched
> More precise NoBeanFoundException information
