thecodingmachine/tdbm

- composer.json
- src/TDBMSchemaAnalyzer.php
- tests/Fixtures/tdbmunittest.sql
When some foreign keys are declared in duplicate, we are facing double declaration of methods.
This patch fixes the problem by ignoring the additional redundant foreign keys.
> Adding checks when some foreign keys are duplicated.

- src/InnerResultIterator.php
- src/TDBMService.php
Route cause: the rowCount() method of DBAL is not portable for SELECT statements. It is in particular not compatible with Oracle.
Put in place a workaround when not using MySQL.
> Fixing "getById() fails on Oracle."

- composer.json
- doc/quickstart.md
- src/InnerResultIterator.php
- src/QueryFactory/AbstractQueryFactory.php
- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- src/TDBMService.php
- src/Utils/TDBMDaoGenerator.php
- tests/Dao/TestCountryDao.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMServiceTest.php
Added class `FindObjectsFromRawSqlQueryFactory` to handle object retrieving on full SQL queries.
It's particularly usefull on complex queries using `GROUP BY` and so on
For example:
```mysql
SELECT country.* AS ids
FROM country
JOIN users ON country.id= users.country_id
GROUP BY country.id
ORDER BY COUNT(users.id);
```
*Note: selecting the columns group `*` from the main table is mandatory!*
> Feature: raw sql

- src/DbRow.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
If a foreign key points to a non primary key, the getters for the objets fail.
Adding failing test first.
> A reference to a non primary key fails

- src/Utils/TDBMDaoGenerator.php
When generating abstract Dao class, PHPDoc for method `findAll` mentions a bean class that may differ from actual returned class.
> Fix bean name in generated Dao

- .scrutinizer.yml
- src/DbRow.php
- src/TDBMService.php
- tests/TDBMDaoGeneratorTest.php
This fixes issues where a new bean is referencing an existing bean that has been modified to point itself to a new bean.
The calls to getDbRow where recursive and this was not necessary, wreaking havok down the line on beans that where not saved further down the hierarchy.
> Fixing issue with cascading save

- src/TDBMService.php
- tests/TDBMServiceTest.php
The previous exception message only displayed the table name. Now, it will also display the value(s) of the primary key(s).
Ex:
`No result found for query on table 'members' for 'idmember' = 12`
> Exception message updated when no result found for primary key(s)

- .gitignore
- .travis.yml
- composer-require-checker.json
- composer.json
- vendor-bin/require-checker/composer.json
- vendor-bin/require-checker/composer.lock
Enables us to detect symbols missing from direct composer dependencies
> Adding composer-require-checker to CI

- .travis.yml
- phpstan.neon
- src/InnerResultIterator.php
- src/ObjectStorageInterface.php
- src/StandardObjectStorage.php
- src/WeakrefObjectStorage.php
- tests/StandardObjectStorageTest.php
- tests/WeakrefObjectStorageTest.php
See #80.
This PR solves the problem by removing the "has" method from the StorageInterface and removing all calls to $weakRef->valid() if they can be replaced by a $weakRef->get() + a check on a null return value.
> Weakref issue: the garbage collector can be triggered between "has" and "get"

- src/Utils/TDBMDaoGenerator.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
Decimal type is mapped by DBAL to string, so we should map it to string.
See #81
> Decimal type should be mapped to string

- src/TDBMSchemaAnalyzer.php
The TDBMSchemaAnalyzer and the SchemaAnalyzer were sharing a common cache key but they do not store the same thing in the cache key (one stores the schema and the other stores the schema with modified date column types switched to immutable)
> Fixing colliding cache key for the schema

- src/DbRow.php
- src/QueryFactory/FindObjectsQueryFactory.php
- src/TDBMService.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/TDBMSchemaAnalyzerTest.php
There was a problem when a primary key containing several columns, one of which is a foreign key was used.
The Storage was not correctly holding reference data to the bean.
This PR fixes the issue.
Related to #93
> Fixing multiple primary key with foreign key issue

- CHANGELOG.md
- doc/annotations.md
- src/Utils/Annotation/AnnotationParser.php
- src/Utils/Annotation/ProtectedGetter.php
- src/Utils/Annotation/ProtectedOneToMany.php
- src/Utils/Annotation/ProtectedSetter.php
- src/Utils/BeanDescriptor.php
- src/Utils/DirectForeignKeyMethodDescriptor.php
- src/Utils/ForeignKeyAnalyzerTrait.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/Utils/DirectForeignKeyMethodDescriptorTest.php
This PR adds the ability to make generated getters and setters protected instead of public using annotations in the DB column.
This enables to develop non-anemic beans.
> Adding @ProtectedGetter and @ProtectedSetter annotation

- phpstan.neon
- src/AbstractTDBMObject.php
- src/DbRow.php
- src/Schema/ForeignKey.php
- src/Schema/ForeignKeys.php
- src/TDBMService.php
- src/Utils/BeanDescriptor.php
- src/Utils/DirectForeignKeyMethodDescriptor.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- UserA generates keys:
- `key1`: `local(dist_1_id) => dist_1(id)`
- `key2`: `local(dist_2_id) => dist_2(id)`
- UserB generates keys: (inversed)
- `key1`: `local(dist_2_id) => dist_2(id)`
- `key2`: `local(dist_1_id) => dist_1(id)`
Use of SQL Foreign Key names could cause conflict on auto-generated key. Each users will have different files, and on Database Query on `key1` UserA will retrieve `dist_1` while UserB will retrieve `dist_2`
Key names are internal and doesn't depend on SQL keys so both users will retrieve the same object
> Generate our own FK names and cache to avoid conflict on generated files

- src/QueryFactory/FindObjectsQueryFactory.php
- src/TDBMService.php
- src/UncheckedOrderBy.php
This new cache can speed up to 20% repeated requests.
> Performance: adding cache for results of FindObjectsQueryFactory::compute

- src/TDBMService.php
When sending parameter with OR, the parenthesis are misplaced (by MagicQuery ?)
There are only parenthesis around AND, but not around OR
> Added parenthesis around AND in filters array

- phpstan.neon
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- vendor-bin/couscous/composer.lock
- vendor-bin/require-checker/composer.lock
Previously : the setter of a resource typed column wouldn't accept null parameter, even if the column was nullable
> Add the possibility to give a null parameter if the column of type resource is nullable

- doc/graphqlite.md
- src/Utils/BeanDescriptor.php
- tests/TDBMDaoGeneratorTest.php
They are currently not abstract. This is probably a regression introduced in TDBM 5.1
> Base DAOs and beans should be abstract

- .travis.yml
- composer.json
- tests/phpunit-mysql8.sh
Now that PHP-SQL-Parser 4.3.0 is released (https://github.com/greenlion/PHP-SQL-Parser/releases/tag/4.3.0) \o/, we can enable PHP 7.3 tests again.
>  Enabling PHP 7.3 tests again 

- .travis.yml
- src/Utils/BeanDescriptor.php
In TDBM5 `findBy` methods order often change (without any apparent reason). This PR aims to sort methods by name so this won't happen again.
> FindBy Method Generation: Order method by name

- src/Utils/BeanDescriptor.php
- src/Utils/DirectForeignKeyMethodDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
- tests/Utils/DirectForeignKeyMethodDescriptorTest.php
Test And Implementation of OneToOne inverse getter
Closes #150
> OneToOne inverse getter

- src/AlterableResultIterator.php
- src/InnerResultIterator.php
- tests/TDBMDaoGeneratorTest.php
Previously this would have execute the query under MySQL, on large result set the executed query could have slow the application
> InnerResultIterator: Improve count() performance of non-executed query

- composer.json
- doc/quickstart.md
- phpstan.neon
- src/QueryFactory/AbstractQueryFactory.php
- src/QueryFactory/FindObjectsFromRawSqlQueryFactory.php
- src/QueryFactory/FindObjectsFromSqlQueryFactory.php
- src/QueryFactory/FindObjectsQueryFactory.php
- src/QueryFactory/QueryFactory.php
- src/ResultIterator.php
- src/TDBMService.php
- tests/Dao/TestArticleDao.php
- tests/Dao/TestArticleSubQueryDao.php
- tests/QueryFactory/FindObjectsFromRawSqlQueryFactoryTest.php
- tests/TDBMDaoGeneratorTest.php
- vendor-bin/couscous/composer.lock
- vendor-bin/require-checker/composer.lock
This PR implements #144 .
It allows filtering a query using another result iterator.
> Filtering by result iterator

- src/AlterableResultIterator.php
- src/EmptyInnerResultIterator.php
- src/InnerResultArray.php
- src/InnerResultIterator.php
- src/InnerResultIteratorInterface.php
- src/MapIterator.php
- src/PageIterator.php
- src/ResultIterator.php
- tests/EmptyInnerResultIteratorTest.php
- tests/MapIteratorTest.php
Migrates the EmptyInnerResultIterator out of the class InnerResultIterator.
In the future, we will be able to create a "StaticInnerResultIterator" containing a static array.
> Creating an abstraction on top of InnerResultIterator

- src/InnerResultArray.php
- src/InnerResultIterator.php
Doing a right  join can create a row with no value, which doesn't make sense and create exception later
> fixed a bug when doing a right join

- .travis.yml
- composer-require-checker.json
- phpstan.neon
- src/NativeWeakrefObjectStorage.php
- src/TDBMService.php
- tests/Commands/GenerateCommandTest.php
- tests/TDBMDaoGeneratorTest.php
PHP 7.4 adds native support for WeakReferences.
There will be no need for the weakref extension (that was incompatible with PHP 7.3).
This PR adds support for these new Weakrefences.
> Adding support for native WeakReferences

- doc/annotations.md
- phpstan.neon
- src/Utils/AbstractBeanPropertyDescriptor.php
- src/Utils/Annotation/AnnotationParser.php
- src/Utils/Annotation/ReadOnly.php
- src/Utils/BeanDescriptor.php
- src/Utils/ObjectBeanPropertyDescriptor.php
- src/Utils/ScalarBeanPropertyDescriptor.php
- tests/TDBMAbstractServiceTest.php
- tests/TDBMDaoGeneratorTest.php
The goal of this annotation is to make a column completely disappear from the constructor and from the setter.
This is useful for computed/generated columns that are dynamically computed by the DBMS.
Closes #214
> Adding a @ReadOnly annotation

- .github/workflows/continuous-integration.yml
This is needed by codecov, otherwise, we can't have a code coverage comparison.
> Making sure CI runs on push on master

- composer.json
Unless test classes are actually used in other projects tests, which seems like a very bad habit to me, I think we don't need to distribute them. Same goes for code checks. Only doubt is the exclusion of all hidden files (`.*`)
> Dist - Exclude test/CI files from composer archive

- src/Utils/BeanDescriptor.php
This is a proposition, not breaking current tests, but leading to potential breaking changes for people using this package.
Considering this schema:
```php
$db->table('foo')
->id()
->column('bar_id')->references('bar');
$db->table('bar')
->id()
->column('foo_id')->references('foo')->unique();
```
Current code will generate getters `FooBaseBean::getBarObject()` and `FooBaseBean::getBarByUniqueFooId()`, whether this request aims to generate `FooBaseBean::getBar()` instead of `FooBaseBean::getBarObject()`. Same transformation applies for setter and Json serialization.
> Improvement - Do not use alternative method name for first occurrence

- src/AbstractTDBMObject.php
- src/DbRow.php
- src/ResultIterator.php
- src/TDBMService.php
- src/Utils/BeanDescriptor.php
- src/Utils/ManyToManyRelationshipPathDescriptor.php
- Add missing/Fix wrong declarations in function signatures (mostly `$beanClasse`/`$resultIteratorClass`)
- Add assert when building class strings from concatenation
- Bypass check in code generator (since `use` statement distorts `class-string` expectation from Laminas' class generator)
> PHPStan - Fix `class-string` parameters

- src/DbRow.php
Issue fixed by selecting the suitable DB row amongst many, instead of using the first by default, given that its primary key columns may use different names.
> Fix - Foreign key broken when referenced table inherits another with pk renamed

- src/Utils/BeanDescriptor.php
To fully support post php7 version, jsonSerialize's signature need to be as "mixed"
See documentation at: https://www.php.net/manual/fr/jsonserializable.jsonserialize.php
This PR allow PHP8's Opcache preloading to run on symfony when using TDBM (as in https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading)
> Adding mixed return type to bean's jsonSerialize

- src/Utils/BeanDescriptor.php
There is an 8-space redundancy, as they were provided in the method body but also seem to be appended by the generator itself.
> Chore - Fix indentation in generated methods 'find'/'findOne'

- composer.json
CI was failing on `composer install` due to this plugin being blocked.
> Fix - Allow composer plugins 'bamarni/composer-bin-plugin'

- composer.json
- doc/limit_offset_resultset.md
- src/AlterableResultIterator.php
- src/PageArray.php
- src/PageInterface.php
- src/PageIterator.php
- src/ResultInterface.php
- src/ResultIterator.php
- tests/Dao/TestCountryDao.php
- tests/TDBMServiceTest.php
[`beberlei/porpaginas`](https://github.com/beberlei/porpaginas) seems to be no longer maintained, and is incompatible with PHP 8.1, due to covariance violations with implemented native interfaces.
Consequently, this aims to replace the code used from Porpaginas (limited to a very small set of interfaces and classes) with self-owned code, compatible with PHP 8.1.
> Chore - Replace Porpaginas with self-owned code

- src/InnerResultIterator.php
When using Grapqlite(https://graphqlite.thecodingmachine.io/) for any grapqhl fields using the following method `retrieveManyToOneRelationshipsStorage` will fail when you call count on graphql.
> Fix: TDBM issue in InnerResultIterator

- src/NativeWeakrefObjectStorage.php
- src/ObjectStorageInterface.php
- src/TDBMService.php
This method can be used to cleanup every bean so long-running process won't keep old data.
> :sparkles: Add `TDBMService::clearBeanCache` method
